name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
      - name: Run build  
        working-directory: ./clean-ecommerce-api 
        run: |
          npm install
          npm build

  test:
    runs-on: ubuntu-latest
    needs: [build] 
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
      - name: Run tests
        working-directory: ./clean-ecommerce-api
        run: |
          npm install
          npm test
